#  Copyright 2022 Arseniy Poroshin
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.


methods:

  ru21:  # 21 letters in the alphabet. And an apostrophe.
    word_pattern: '[А-ЯЁа-яё]'
    steps:
      # Additional exceptions should go here, at the top.
      - зх: z'h
        сх: s'h
        цх: c'h
      - а: a
        б: b
        в: v
        г: g
        д: d
        е: e
        ё: e
        ж: zh
        з: z
        и: i
        к: k
        л: l
        м: m
        н: n
        о: o
        п: p
        р: r
        с: s
        т: t
        у: u
        ф: f
        х: h
        ц: c
        ч: ch
        ш: sh
        щ: sh
        ъ: <lssep>
        ы: i
        ь: <lssep>
        э: e
      - ai: a'i
        ei: e'i
        ia: i'a
        ii: i'i
        io: i'o
        iu: i'u
        oi: o'i
        ui: u'i
      - ai: a'i
        ei: e'i
        ia: i'a
        ii: i'i
        io: i'o
        iu: i'u
        oi: o'i
        ui: u'i
      - й: i
        ю: iu
        я: ia
      - <lssep>e: "'e"
        <lssep>i: "'i"
      - <lssep>: ""


  "ru_s'esh_je_yeshë_etih":
    word_pattern: '[А-ЯЁа-яё]'
    steps:
      - кс: x
        кз: x
        гз: x
      - а: <lsvwl>a
        б: b
        в: v
        г: g
        д: d
        е: <lsvwl>e
        ё: <lsvwl>ë
        ж: j
        з: z
        и: <lsvwl>i
        ий: <lsvwl>y
        й: y
        к: k
        л: l
        м: m
        н: n
        о: <lsvwl>o
        п: p
        р: r
        с: s
        сх: s'h
        т: t
        у: <lsvwl>u
        ф: f
        х: h
        ц: c
        цх: c'h
        ч: ch
        ш: sh
        щ: sh
        ъ: <lssep>
        ы: <lsvwl>i
        ый: <lsvwl>y
        ь: <lssep>
        э: <lsvwl>e
        ю: <lsvwl>ü
        я: <lsvwl>ä
      - <lssep><lsvwl>: "'"
      - <lssep>: ''
        <lsvwl>: ''

  ru_sjeshj_zhe_escho_etih:
    word_pattern: '[А-ЯЁа-яё]'
    steps:
      - кв: qu
        кс: x
        кз: x
        гз: x
      - а: a
        б: b
        в: v
        г: g
        д: d
        е: e
        ё: yo
        ж: zh<rlnoy>
        з: z
        и: i
        й: y
        к: k
        л: l
        м: m
        н: n
        о: o
        п: p
        р: r
        с: s
        т: t
        у: u
        ф: f
        х: h<rlnoy>
        ц: c
        ч: ch<rlnoy>
        ш: sh<rlnoy>
        щ: sch<rlnoy>
        ъ: j<rlnoy>
        ы: y
        ь: j<rlnoy>
        э: e
        ю: yu
        я: ya
      - <rlnoy>y: ''
        <rlnoy>: ''

  ru_syeshj_zhe_yescho_etih:
    word_pattern: '[А-ЯЁа-яё]'
    steps:
      - кв: qu
        кс: x
        кз: x
        гз: x
      - а: a
        б: b<xt>
        в: v<xt>
        г: g<xt>
        д: d<xt>
        е: ye
        ё: yo
        ж: zh<xt>
        з: z<xt>
        и: i
        й: y<xt>
        к: k<xt>
        л: l<xt>
        м: m<xt>
        н: n<xt>
        о: o
        п: p<xt>
        р: r<xt>
        с: s<xt>
        т: t<xt>
        у: u
        ф: f<xt>
        х: h<xt>
        ц: c<xt>
        ч: ch<xt>
        ш: sh<xt>
        щ: sch<xt>
        ъ: j<rlsep>
        ь: j<rlsep>
        ьи: j<rlsep>yi
        э: e
        ю: yu
        я: ya
      - <xt>y: <xt>j
        <xt>ye: <xt>e
        <xt>: ''
      - ы: y
      - h<xt>j: h<xt>
      - j<rlsep>y: y
      - <rlsep>: ''
        <xt>: ''

  ru_ji:
    word_pattern: '[А-ЯЁа-яё]'
    steps:
      - кв: qu
        кс: x
        кз: x
        гз: x
      - а: a
        б: b<xt>
        в: v<xt>
        г: g<xt>
        д: d<xt>
        е: ye
        ё: yo
        ж: zh<xt>
        з: z<xt>
        и: i
        й: y<xt>
        к: k<xt>
        л: l<xt>
        м: m<xt>
        н: n<xt>
        о: o
        п: p<xt>
        р: r<xt>
        с: s<xt>
        т: t<xt>
        у: u
        ф: f<xt>
        х: h<xt>
        ц: c<xt>
        ч: ch<xt>
        ш: sh<xt>
        щ: sch<xt>
        ъ: j<rlsep>
        ы: ji
        ь: j<rlsep>
        ьи: j<rlsep>yi
        э: e
        ю: yu
        я: ya
      - <xt>y: <xt>j
        <xt>ye: <xt>e
        <xt>: ''
      - c<xt>j: h<xt>
        h<xt>j: h<xt>
      - j<rlsep>y: y
      - <rlsep>: ''
        <xt>: ''

  ru_syešj_že_yesčo_etih:
    word_pattern: '[А-ЯЁа-яё]'
    steps:
      - кв: qu
        кс: x
        кз: x
        гз: x
      - а: a
        б: b<xt>
        в: v<xt>
        г: g<xt>
        д: d<xt>
        е: ye
        ё: yo
        ж: ž<shxt><xt>
        з: z<xt>
        и: i
        й: y<xt>
        к: k<xt>
        л: l<xt>
        м: m<xt>
        н: n<xt>
        о: o
        п: p<xt>
        р: r<xt>
        с: s<xt>
        т: t<xt>
        у: u
        ф: f<xt>
        х: h<xt>
        ц: c<xt>
        ч: č<shxt><xt>
        ш: š<shxt><xt>
        щ: sč<shxt><xt>
        ъ: j<rlsep>
        ь: j<rlsep>
        ьи: j<rlsep>yi
        э: e
        ю: yu
        я: ya
      - <xt>y: <xt>j
        <xt>ya: <xt>ä
        <xt>ye: <xt>e
        <xt>yo: <xt>ö
        <xt>yu: <xt>ü
        <xt>: ''
      - ы: y
      - <shxt><xt>j: <shxt><xt>
        <shxt><xt>ä: <shxt><xt>a
        <shxt><xt>ö: <shxt><xt>o
        <shxt><xt>ü: <shxt><xt>u
      - j<rlsep>y: y
      - <rlsep>: ''
        <xt>: ''
        <shxt>: ''

  uk1:
    word_pattern: "[А-ЩЬЮЯҐЄІЇа-щьюяґєії'`’ʼ]"
    steps:
      - кв: qu
        кс: x
        кз: x
        ґз: x
      - а: a
        б: b<xt>
        в: v<xt>
        г: h<xt>
        ґ: g<xt>
        д: d<xt>
        е: e
        є: ye
        ж: zh<xt>
        з: z<xt>
        і: i
        ї: yi
        й: y<xt>
        к: k<xt>
        л: l<xt>
        м: m<xt>
        н: n<xt>
        о: o
        п: p<xt>
        р: r<xt>
        с: s<xt>
        т: t<xt>
        у: u
        ф: f<xt>
        х: kh<xt>
        ц: c<xt>
        ч: ch<xt>
        ш: sh<xt>
        щ: shch<xt>
        ь: j
        ю: yu
        я: ya
      - <xt>y: <xt>j
      - и: y
      - h<xt>j: h<xt>
      - "<xt>'": "<xt>"
        "<xt>`": "<xt>"
        "<xt>’": "<xt>"
        "<xt>ʼ": "<xt>"
      - <xt>: ''

  uk2:
    word_pattern: "[А-ЩЬЮЯҐЄІЇа-щьюяґєії'`’ʼ]"
    steps:
      - кв: qu
        кс: x
        кз: x
        ґз: x
      - а: a
        б: b<xt>
        в: v<xt>
        г: h<xt>
        ґ: g<xt>
        д: d<xt>
        е: e
        є: ye
        ж: zh<xt>
        з: z<xt>
        і: i
        ї: ï
        й: y<xt>
        к: k<xt>
        л: l<xt>
        м: m<xt>
        н: n<xt>
        о: o
        п: p<xt>
        р: r<xt>
        с: s<xt>
        т: t<xt>
        у: u
        ф: f<xt>
        х: kh<xt>
        ц: c<xt>
        ч: ch<xt>
        ш: sh<xt>
        щ: shch<xt>
        ь: j
        ю: yu
        я: ya
      - <xt>y: <xt>j
      - и: y
      - h<xt>j: h<xt>
      - "<xt>'": "<xt>"
        "<xt>`": "<xt>"
        "<xt>’": "<xt>"
        "<xt>ʼ": "<xt>"
      - <xt>: ''

  uk3:
    word_pattern: "[А-ЩЬЮЯҐЄІЇа-щьюяґєії'`’ʼ]"
    steps:
      - кв: qu
        кс: x
        кз: x
        ґз: x
      - а: a
        б: b<xt>
        в: v<xt>
        г: h<xt>
        ґ: g<xt>
        д: d<xt>
        е: e
        є: ye
        ж: ž<xt>
        з: z<xt>
        і: i
        ї: ï
        й: y<xt>
        к: k<xt>
        л: l<xt>
        м: m<xt>
        н: n<xt>
        о: o
        п: p<xt>
        р: r<xt>
        с: s<xt>
        т: t<xt>
        у: u
        ф: f<xt>
        х: kh<xt>
        ц: c<xt>
        ч: č<xt>
        ш: š<xt>
        щ: šč<xt>
        ь: j
        ю: yu
        я: ya
      - <xt>y: <xt>j
        <xt>ya: <xt>ä
        <xt>ye: <xt>ë
        <xt>yu: <xt>ü
      - и: y
      - h<xt>j: h<xt>
        h<xt>ä: h<xt>a
        h<xt>ë: h<xt>e
        h<xt>ü: h<xt>u
      - "<xt>'": "<xt>"
        "<xt>`": "<xt>"
        "<xt>’": "<xt>"
        "<xt>ʼ": "<xt>"
      - <xt>: ''

  ru_сьешь_же_ещё_етих:
    word_pattern: '[А-ЯЁа-яё]'
    steps:
      - а: а
        б: б
        в: в
        г: г
        д: д
        е: е
        ё: ё
        ж: ж
        з: з
        и: и
        й: й
        к: к
        л: л
        м: м
        н: н
        о: о
        п: п
        р: р
        с: с
        т: т
        у: у
        ф: ф
        х: х
        ц: ц
        ч: ч
        ш: ш
        щ: щ
        ъ: ь
        ы: ы
        ь: ь
        э: е
        ю: ю
        я: я

  "en-jqxz":
    word_pattern: [A-Za-z]
    steps:
      - ja: gia
        je: ge
        ji: gi
        jo: gio
        ju: giu
        jy: gy
        x: cs
        qu: cw
        z: s
      - j: dge